---
additional:
- template-dockerhub-release
- bkwholesale/spider

files:
- '!README.md'
- '!**/sync.yml'
- '!Dockerfile'
- '!.secrets.baseline'
- '!**/template-sync.yml'
- '!.github/workflows/sync.yml'
